learning_users/basicapp/urls.py
from django.urls import path
from basicapp import views


#template URLs

app_name = 'basicapp'

urlpatterns=[
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
]

learning_users/learning_users/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.urls import path
from basicapp import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basicapp/',include('basicapp.urls')),
    path('logout/',views.user_logout,name='logout'),
]

learning_users/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    #course does not account for required on delete when inheriting from other models

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    #additional classes
    Portfolio_site = models.URLField(blank=True)

    Profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

learning_users/basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('Portfolio_site','Profile_pic')

learning_users/basicapp/views.py
from django.shortcuts import render
from basicapp.forms import UserForm,UserProfileInfoForm

#login imports
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required




# Create your views here.

def index(request):
    return render(request,'basicapp/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
         user_form = UserForm()
         profile_form = UserProfileInfoForm()

    return render(request,'basicapp/registration.html',
                            {'user_form':user_form,
                              'profile_form':profile_form,
                              'registered':registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:

            if user.is_active:

                login(request,user)

                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("someone tried to login and failed")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("invalid details")
    else:
        return render(request,'basicapp/login.html',{})

learning_users/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <nav class ='navbar navbar-expand-md navbar-dark fixed-top bg-dark'>

        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="nav navbar-nav mr-auto">
            <li class="nav-item">
              <a class="navbar-brand" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'basicapp:register' %}">Register</a>
            </li>

            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'basicapp:user_login' %}">Login</a>
            </li>
            {% endif %}

          </ul>
        </div>
   </nav>

   <div class="container">
     {% block body_block %}
     {% endblock %}
   </div>


  </body>
</html>

learning_users/templates/basicapp/index.html
{% extends "basicapp/base.html" %}}
{% block body_block %}

<div class="jumbotron">
  <h1>Django Level Five exercise</h1>

</div>
{% endblock %}

learning_users/templates/basicapp/login.html
{% extends 'basicapp/base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>Please login</h1>

  <form action="{% url 'basicapp:user_login' %}" method="post">
    {%csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password"></label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">
  </form>

</div>
{% endblock %}

learning_users/templates/basicapp/registration.html
{% extends 'basicapp/base.html' %}
{% load staticfiles %}

{% block body_block %}

<div class="jumbotron">
  {% if registered %}
    <h1>Thank you for registering</h1>
  {% else %}
    <h1>Register here</h1>
    <h3>Fill out the form:</h3>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register">

    </form>

  {% endif %}

</div>

{% endblock %}